### ISSUE TITLE
Resolve Overdrive GET request issue

### ISSUE THREAD

**Issue by emanuelfeld** [emanuelfeld/booksfordc#13]
Able to search Overdrive using the following URL:
"http://overdrive.dclibrary.org/BANGSearch.dll?Type=FullText&PerPage=24&URL=SearchResults.htm&Sort=SortBy%3DRelevancy&FullTextField=All&FullTextCriteria={INSERT_QUERY_HERE}&x=0&y=0"

e.g. http://overdrive.dclibrary.org/BANGSearch.dll?Type=FullText&PerPage=24&URL=SearchResults.htm&Sort=SortBy%3DRelevancy&FullTextField=All&FullTextCriteria=Hello&x=0&y=0

But jquery GET request of that URL does not load response data. I'm not sure if it's an issue of cookie-setting.

![image](https://cloud.githubusercontent.com/assets/4269640/6515448/e5fab5e0-c357-11e4-9e78-a7f442e4e02d.png)

It would be nice to have this functionality, since not all ebooks in Overdrive are also searchable in the catalog, for some reason.

**Comment by evonfriedland** [comment]
Search url: http://overdrive.dclibrary.org/en/BANGSearch.dll

**Comment by cmgiven** [comment]
So this is not an AJAX issue, nor a cookies issue, at least as far as I can tell.

A 302 is a temporary redirect, indicating that the requested content is at a different location. The first page (looking at your Chrome activity) redirects to the second, which redirects to the third, which redirects to the error page (which improperly returns a 200 status). No matter how you access it, you'll hit the first two redirects, which look like they (1) assign your search a unique ID and (2) fix the capitalization of the query keys returned by the first redirect. It's the third redirect that's the problem, and I'm struggling to understand why it's happening (or not happening).

My testing results so far:

browser: works!
curl: does not work :(
[hurl.it](https://www.hurl.it) (stepping manually through each redirect): does not work :(
[hurl.it](https://www.hurl.it) with the "Follow redirects" feature turned on: works (WTF?)

Why does the last one work while the following the redirects one at a time does not? No idea, although the fact that it does probably rules out cookies or header sniffing as the culprit. I'm not sure if there's some secret magic that hurl.it is performing that curl doesn't know about when it tries to follow the redirects.

As far as I can tell, the request the browser makes for the third page does not differ from the requests I've made manually in hurl.it. I've tried adding all of the parameters from any request to that third URL (`searchid=38400590s&y=0&x=0&FullTextField=All&sortby=Relevancy&FullTextCriteria=Hello&PerPage=24`) in an attempt to overcome the stated "A required field does not exist" error message, and modified my request headers to look like the browser. None of the above worked.

I'm stumped...

**Comment by cmgiven** [comment]
Might have an answer. @evonfriedland sent the code for another plugin that does the same thing. Noticed that plugin was making a POST instead of a GET. I thought that was weird, but sure enough...

```
curl --data "Title=hello" -L http://overdrive.dclibrary.org/en/BANGSearch.dll
```

...gives a valid response. Try switching your AJAX GET to POST and see what happens (note that your query string will now be sent in the message body, not in the URL).

**Comment by emanuelfeld** [comment]
Adding a gist write up summarizing the issue: https://gist.github.com/emanuelfeld/7c2c56d3966f15a29c5e

**Comment by emanuelfeld** [comment]
@paultag @cmgiven @thadk Not going to pretend I know exactly why this worked. But I seem to have fixed the Overdrive GET request issue by using background script for cross-site request. Maybe some HTTP/HTTPS mixed content issue?

**Comment by paultag** [comment]
Hunh! Neat! I'll have to dig in anyway to see what was going on, interesting!
