### ISSUE TITLE
Need booksfordc extension logo

### ISSUE THREAD

**Issue by emanuelfeld** [emanuelfeld/booksfordc#2]
In 16px, 48px, 128px squares. Thinking something like this:
![fullsizerender](https://cloud.githubusercontent.com/assets/4269640/6431995/0f639f00-c010-11e4-8af0-304abd73a97a.jpg)

**Comment by ajschumacher** [comment]
Red? Black? Transparent background? White background?

**Comment by emanuelfeld** [comment]
Transparent background and red would be good, I think

**Comment by emanuelfeld** [comment]
@ajschumacher ![fullsizerender](https://cloud.githubusercontent.com/assets/4269640/6477142/aed2f872-c1ed-11e4-9f19-f05fcbf24941.jpg) though hopefully a bit more book-like. I guess it would be good to have it in both black and in red, with transparent backgrounds. Here's a picture of the DC flag ![fullsizerender](https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_Washington%2C_D.C..svg).

**Comment by ajschumacher** [comment]
Awesome. I just placed an order on Fiverr. Let's see if we get anything good back! This is what I said:

> Hi! Hope you're doing well, and thanks for your help making this logo awesome!
> 
> This logo is for a software project connected to Washington, DC public libraries. There's a thread about the logo here:
> 
> https://github.com/evonfriedland/booksfordc/issues/2
> 
> There are images there, but I'll also attach them here.
> 
> The idea is that it should be inspired by the DC flag, but instead of straight bars across the bottom, the silhouettes of two open books.
> 
> We would like a red version and a black version, both with transparent backgrounds.
> 
> Thank you!
> 
> ~ Aaron

**Comment by ajschumacher** [comment]
This is the person doing it: https://www.fiverr.com/gemaniq

Expected delivery time is three days.

**Comment by emanuelfeld** [comment]
Great, thanks Aaron! Are they producing vector graphics or will they just send the images in 16px, 48px, and 128px square versions?

**Comment by ajschumacher** [comment]
Which do you prefer? Both?

**Comment by emanuelfeld** [comment]
Sure, both would be nice if we want to reuse the logo for other purposes.

**Comment by ajschumacher** [comment]
Done!
